config/routes.rb
Rails.application.routes.draw do
  resources :goals
  resources :users do 
    resources :goals do
      get 'complete', to: 'goals#complete'
      get 'reverse', to: 'goals#reverse_completion'
    end
  end
  match 'users/:id', to: 'users#show', via: :post  # what is this for?
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :goals, dependent: :destroy
  accepts_nested_attributes_for :goals # gives us a writer that allows us
  attr_accessor :completed_goals,:incomplete_goals                                 # to update the child class through 
                                   # the parent
  # PASS
  def update_score(additional_points)
    
    self.points += additional_points
  end

  def reverse_score(deduction)
    self.points -= deduction
  end

end


# we use the user model to update goals

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  # GET /goals
  # GET /goals.json
  def index
    @goals = Goal.all
  end

  # GET /goals/1
  # GET /goals/1.json
  def show
  end

  # GET /goals/new
  def new
    @goal = Goal.new
  end

  # GET /goals/1/edit
  def edit
  end

  # POST /goals
  # POST /goals.json
  def create
    @goal = Goal.new(goal_params)
    
    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal, notice: 'Goal was successfully created.' }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goals/1
  # PATCH/PUT /goals/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goals/1
  # DELETE /goals/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # How do I attach this method to a form
  def complete
    @current_goal = Goal.find(params[:goal_id])
    @current_goal.user.update_score(@current_goal.points)
    
    @current_goal.completed = true
    @current_goal.user.save!
    @current_goal.save!
    
    redirect_to user_path(@current_goal.user)
  end

  def reverse_completion
    @current_goal = Goal.find(params[:goal_id])
    @current_goal.user.reverse_score(@current_goal.points)
    
    @current_goal.completed = false
    @current_goal.user.save!
    @current_goal.save!
    
    redirect_to user_path(@current_goal.user)
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def goal_params
      params.require(:goal).permit(:title, :description, :points, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @completed_goals = @user.goals.where(completed: true)
    @incomplete_goals = @user.goals.where(completed: false) # refactor
    @goals = @user.goals    
  end

  # GET /users/new
  def new
    @user = User.new
    @user.goals.build 
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user)
        .permit(:email, :name, :points, goals_attributes: %i[id title description points])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/_form.html.erb
<%= form_with(model: goal, local: true) do |form| %>
  <% if goal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(goal.errors.count, "error") %> prohibited this goal from being saved:</h2>

      <ul>
        <% goal.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :points %>
    <%= form.number_field :points %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/goals/edit.html.erb
<h1>Editing Goal</h1>

<%= render 'form', goal: @goal %>

<%= link_to 'Show', @goal %> |
<%= link_to 'Back', goals_path %>

app/views/goals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Goals</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Points</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goals.each do |goal| %>
      <tr>
        <td><%= goal.title %></td>
        <td><%= goal.description %></td>
        <td><%= goal.points %></td>
        <td><%= goal.user_id %></td>
        <td><%= link_to 'Show', goal %></td>
        <td><%= link_to 'Edit', edit_goal_path(goal) %></td>
        <td><%= link_to 'Destroy', goal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Goal', new_goal_path %>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<%= render 'form', goal: @goal %>

<%= link_to 'Back', goals_path %>

app/views/goals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @goal.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @goal.description %>
</p>

<p>
  <strong>Points:</strong>
  <%= @goal.points %>
</p>

<p>
  <strong>User:</strong>
  <%= @goal.user_id %>
</p>

<%= link_to 'Edit', edit_goal_path(@goal) %> |
<%= link_to 'Back', goals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoalsGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
    <!-- Second navbar for categories -->
      <nav class="navbar navbar-default">
        <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Brand</a>
          </div>
      
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="#">Home</a></li>
              <li><a href="#">About</a></li>
              <li><a href="#">Services</a></li>
              <li><a href="#">Works</a></li>
              <li><a href="#">News</a></li>
              <li><a href="#">Contact</a></li>
              <li>
                <a class="btn btn-default btn-outline btn-circle"  data-toggle="collapse" href="#nav-collapse1" aria-expanded="false" aria-controls="nav-collapse1">Categories</a>
              </li>
            </ul>
            <ul class="collapse nav navbar-nav nav-collapse" id="nav-collapse1">
              <li><a href="#">Web design</a></li>
              <li><a href="#">Development</a></li>
              <li><a href="#">Graphic design</a></li>
              <li><a href="#">Print</a></li>
              <li><a href="#">Motion</a></li>
              <li><a href="#">Mobile apps</a></li>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
      </nav><!-- /.navbar -->

      <div class="col-md-12 col-xs-12 text-center page-header">
        <h1 class="game-name">
            Level Up
            <small>One Goal at a Time</small>    
        </h1>   
      </div>
      <%= yield %>
    </div>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :points %>
    <%= form.number_field :points %>
  </div>


  <%= form.fields_for :goals, user.goals do |goal_form| %>
    <div class="field">
      <%= goal_form.label :title %>
      <%= goal_form.text_field :title %>
    </div>

    <div class="field">
      <%= goal_form.label :description %>
      <%= goal_form.text_field :description %>
    </div>

    <div class="field">
      <%= goal_form.label :points %>
      <%= goal_form.number_field :points %>
    </div>
  <% end %>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div class="user-stats well">
  <h1>Users</h1>

  <table>
    <thead>
      <tr>
        <th>Email</th>
        <th>Name</th>
        <th>Points</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.name %></td>
          <td><%= user.points %></td>
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
  <div class="user-stats well">
    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>

    <p>
      <strong>Name:</strong>
      <%= @user.name %>
    </p>

    <p>
      <strong>POINT TOTAL:</strong>
      <%= @user.points %>
    </p>
  </div>


<div class="user-stats well"> 
    <h2>Goals</h2>

    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Points</th>
          <!-- <th>User</th> -->
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @incomplete_goals.each_with_index do |goal, index| %>
          <tr id=<%= "incomplete_goal_#{index}" %>>
            <td><%= goal.title %></td>
            <td><%= goal.description %></td>
            <td><%= goal.points %></td>
            <td><%= button_to "Complete Goal", user_goal_complete_path(@user, goal), method: :get, form_class: "#" %></td><!--hit a butoon hits complete action for goals. passes along goal id that belongs to particular goal inline-->
          </tr>
        <% end %>
      </tbody>
    </table><br><br><br>
  </div>

<div class="user-stats well">
  <h6>Completed Goals</h6>

  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Points</th>
        <!-- <th>User</th> -->
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @completed_goals.each_with_index do |goal, index| %>
        <tr id=<%= "completed_goal_#{index}" %>>
          <td><%= goal.title %></td>
          <td><%= goal.description %></td>
          <td><%= goal.points %></td>
          <td><%= button_to "Reverse Completion", user_goal_reverse_path(@user, goal), method: :get, form_class: "#" %></td>
          <!-- <td><%= goal.user_id %></td> -->
        </tr>
      <% end %>
    </tbody>
  </table>
</div>